# Site settings
title: Woman In Dev
header-img: img/home-bg.png
email: onuskacc@gmail.com
copyright_name: conuska
description: > # this means to ignore newlines until "baseurl:"
  A woman starting out in tech.
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  conuska
learn_profile: conuska
email_username: onuskacc@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
